<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dish_washing_cobot</name>
  <version>0.0.0</version>
  <description>Doosan M0609 협동로봇으로 접시·그릇·컵을 형상별 궤적으로 세척하는 ROS2 패키지</description>
  <maintainer email="seb000423@gmail.com">seb000423</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>dsr_common2</depend>
  <depend>dsr_msgs</depend>
  <depend>std_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
